filename: "changelog/${issue}-${type}.md"
fields:
    - name: issue
      type: string
    - name: type
      type: string
      enum: [add, change, deprecate, remove, fix, security]
    - name: audience
      type: string
      enum: [user, developer]
    - name: version
      type: semver
      optional: true
    - name: date
      type: date
    - name: components
      type: string
      list: true
      enum: [server, ui, cli]
      optional: true
filterPresets: []
links: []
supportedDateFormat: 'YYYY-MM-DD'
standard:
    query: ""
    sort:
        field: version
        order: desc
