version: 2
basedir: changelog
template:
  file: ${issue}-${type}.md
note:
  links:
    - name: "GitHub#${issue}"
      link: "https://github.com/FACT-Finder/snage/issues/${issue}"
fields:
  - name: issue
    type: number
    description: The github issue number
  - name: type
    type: string
    enum: [ add, change, deprecate, remove, fix, security ]
  - name: audience
    type: string
    enum: [ user, developer ]
    description: The audience affected by the change
  - name: version
    type: semver
    optional: true
    provided:
      by: 'git-version'
      arguments:
        version-regex: '^v(.*)$'
  - name: date
    type: date
    description: date in 'YYYY-MM-DD' format
  - name: components
    type: string
    list: true
    enum: [ server, ui, cli, api, config, docs ]
    optional: true
filterPresets: []
standard:
  query: ""
  sort:
    field: version
    order: desc
