version: 2
basedir: changelog
template:
  file: ${issue}-${type}.md
note:
  styles:
    - on: 'type = add'
      css:
        borderLeft: '10px solid #2ecc71' # green

    - on: 'type = remove'
      css:
        borderLeft: '10px solid black'

    - on: 'type = deprecate'
      css:
        borderLeft: '10px solid #95a5a6' # grey

    - on: 'type = fix'
      css:
        borderLeft: '10px solid #2980b9' # blue

    - on: 'type = security'
      css:
        borderLeft: '10px solid #e74c3c' # red

    - on: 'type = change'
      css:
        borderLeft: '10px solid #f39c12' # orange

  links:
    - name: "GitHub#${issue}"
      link: "https://github.com/FACT-Finder/snage/issues/${issue}"
fields:
  - name: issue
    type: number
    description: The github issue number
  - name: type
    type: string
    enum: [ add, change, deprecate, remove, fix, security ]
    styles:
      - on: 'type = add'
        css:
          background: '#2ecc71' # green
      - on: 'type = remove'
        css:
          background: 'black'
          color: 'white'
      - on: 'type = deprecate'
        css:
          background: '#95a5a6' # grey
      - on: 'type = fix'
        css:
          background: '#2980b9' # blue
          color: 'white'
      - on: 'type = security'
        css:
          background: '#e74c3c' # red
      - on: 'type = change'
        css:
          background: '#f39c12' # orange
  - name: audience
    type: string
    enum: [ user, developer ]
    description: The audience affected by the change
  - name: version
    type: semver
    optional: true
    provided:
      by: 'git-version'
      arguments:
        version-regex: '^v(.*)$'
  - name: date
    type: date
    description: date in 'YYYY-MM-DD' format
  - name: components
    type: string
    list: true
    enum: [ server, ui, cli, api, config, docs ]
    optional: true
filterPresets: []
standard:
  query: ""
  sort:
    field: version
    order: desc
