on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn
      - run: yarn lerna bootstrap
      - run: yarn lerna run test
      - uses: codecov/codecov-action@v1
      - run: yarn lerna run format-check
      - run: yarn lerna run lint-check
      - run: yarn lerna run build
        env:
          BUILD_VERSION: ${GITHUB_REF/refs\/tags\/v/}
      - name: Update changelog
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          git config user.email "snage@snage"
          git config user.name "SnageCI"

          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/FACT-Finder/snage.git
          git fetch origin $GIT_BRANCH
          git checkout $GIT_BRANCH

          yarn --cwd packages/snage dev --config $PWD/.snage.yaml set --on 'version absent' version $VERSION
          yarn --cwd packages/snage dev --config $PWD/.snage.yaml set --on 'date absent' date `date +%F`

          git add changelog
          git diff --staged --quiet || (git commit -m "Update changelog"; git push origin $GIT_BRANCH)
        env:
          VERSION: ${GITHUB_REF/refs\/tags\/v/}
          GIT_BRANCH: 'master'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to Docker and NPM
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > $HOME/.npmrc
          docker build -t snage/snage:${VERSION} packages/snage
          docker push     snage/snage:${VERSION}
          (cd packages/snage && yarn publish --new-version "${VERSION}" --no-git-tag-version)
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          VERSION: ${GITHUB_REF/refs\/tags\/v/}
