name: build
on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --prune --unshallow
      - uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'
      - name: cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node_modules-
      - run: yarn --frozen-lockfile
      - run: yarn docs build
      - run: yarn lerna run test
      - uses: codecov/codecov-action@v5.4.2
      - run: yarn lerna run format-check
      - run: yarn lerna run lint-check
      - run: yarn lerna run build
