on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn
      - run: yarn lerna bootstrap
      - run: yarn lerna run test
      - uses: codecov/codecov-action@v1
      - run: yarn lerna run format-check
      - run: yarn lerna run lint-check
      - run: yarn lerna run build
        env:
          BUILD_VERSION: ${GITHUB_REF/refs\/tags\/v/}
      - if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > $HOME/.npmrc
          docker build -t snage/snage:${GITHUB_REF/refs\/tags\/v/} packages/snage
          docker push     snage/snage:${GITHUB_REF/refs\/tags\/v/}
          (cd packages/snage && yarn publish --new-version "${GITHUB_REF/refs\/tags\/v/}" --no-git-tag-version)
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
