name: deploy
on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node_modules-
      - run: yarn --frozen-lockfile
      - name: Get Version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - run: yarn docs build
      - run: yarn lerna run build
        env:
          BUILD_VERSION: ${{ env.VERSION }}
      - name: upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: packages/snage/build/npm
      - name: upload docs artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: site

  deploy-docker-unstable:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: packages/snage/build/npm
      - name: Publish master as snage/snage:unstable to Docker
        run: |
          echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > $HOME/.npmrc
          docker build -t snage/snage:unstable packages/snage
          docker push     snage/snage:unstable
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

  deploy-snage-changelog:
    runs-on: ubuntu-latest
    needs: deploy-docker-unstable
    steps:
      - uses: actions/checkout@v2
      - name: Deploy changelog.snage.dev
        run: |
          export ANSIBLE_PRIVATE_KEY_FILE="$HOME/id_rsa"
          echo "$SSH_KEY" > $HOME/id_rsa
          chmod 600 $HOME/id_rsa
          ansible-playbook -i root@changelog.snage.dev, -e "SNAGE_VERSION=unstable" ansible/deploy-snage.yml
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          ANSIBLE_HOST_KEY_CHECKING: false

  deploy-github-pages:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: docs
          path: site
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          BRANCH: gh-pages
          FOLDER: site
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
